### ISSUE TITLE
Failed to run CUDA examples 

### ISSUE THREAD

**Issue by ghost** [STEllAR-GROUP/tutorials#7]
Hi, I built HPX with CUDA with the following CMake command:
```
cmake -GNinja -DHPX_WITH_CUDA=ON -DCMAKE_INSTALL_PREFIX=/path/to/hpx/install -DHPX_WITH_MALLOC=system -DHPX_WITH_CXX2A=ON -DHPX_WITH_MAX_CPU_COUNT=8 -DHPX_WITH_APEX=TRUE -DAPEX_WITH_OTF2=TRUE -DOTF2_ROOT=/path/to/otf2/install -DAPEX_WITH_CUDA=TRUE .. && ninja install
```

I wasn't able to build any of the CUDA examples. For example when compiling (https://github.com/STEllAR-GROUP/tutorials/blob/master/examples/00_exercises/solution9.cpp), I get the following error:
```
../solution9.cpp: In function ‘int main()’:
../solution9.cpp:16:42: error: ‘cuda’ in namespace ‘hpx::compute’ does not name a type
     using allocator_type = hpx::compute::cuda::default_allocator;
                                          ^~~~
../solution9.cpp:17:41: error: ‘cuda’ in namespace ‘hpx::compute’ does not name a type
     using executor_type = hpx::compute::cuda::default_executor;
                                         ^~~~
../solution9.cpp:28:19: error: ‘hpx::compute::cuda’ has not been declared
     hpx::compute::cuda::target device;
                   ^~~~
../solution9.cpp:31:5: error: ‘allocator_type’ was not declared in this scope
     allocator_type alloc(device);
     ^~~~~~~~~~~~~~
../solution9.cpp:31:5: note: suggested alternative: ‘fallocate’
     allocator_type alloc(device);
     ^~~~~~~~~~~~~~
     fallocate
../solution9.cpp:32:5: error: ‘executor_type’ was not declared in this scope
     executor_type exec(device);
     ^~~~~~~~~~~~~
../solution9.cpp:41:48: error: type/value mismatch at argument 2 in template parameter list for ‘template<class T, class Allocator> class hpx::compute::vector’
     hpx::compute::vector<double, allocator_type> c(1000000, 2.0, alloc);
                                                ^
../solution9.cpp:41:48: note:   expected a type, got ‘allocator_type’
../solution9.cpp:41:66: error: ‘alloc’ was not declared in this scope
     hpx::compute::vector<double, allocator_type> c(1000000, 2.0, alloc);
                                                                  ^~~~~
../solution9.cpp:41:66: note: suggested alternative: ‘valloc’
     hpx::compute::vector<double, allocator_type> c(1000000, 2.0, alloc);
                                                                  ^~~~~
                                                                  valloc
../solution9.cpp:41:71: error: expression list treated as compound expression in initializer [-fpermissive]
     hpx::compute::vector<double, allocator_type> c(1000000, 2.0, alloc);
                                                                       ^
../solution9.cpp:44:60: error: ‘exec’ was not declared in this scope
     hpx::parallel::reduce(hpx::parallel::execution::par.on(exec), std::begin(v),
                                                            ^~~~
../solution9.cpp:44:60: note: suggested alternative: ‘rexec’
     hpx::parallel::reduce(hpx::parallel::execution::par.on(exec), std::begin(v),
                                                            ^~~~
                                                            rexec
../solution9.cpp:44:78: error: ‘v’ was not declared in this scope
     hpx::parallel::reduce(hpx::parallel::execution::par.on(exec), std::begin(v),
                                                                              ^
ninja: build stopped: subcommand failed.

```

I modified the code to reflect current HPX changes (like `hpx::compute::cuda::default_allocator` to `hpx::cuda::experimental::default_allocator`) but I kept gettiing `error: ‘cuda’ is not a member of ‘hpx’`.

**Comment by msimberg** [comment]
Hi @nithin-nod, thanks for pointing this out and sorry about that. I've let the exercises go slightly out of date with HPX master. Since you seem to be building HPX yourself, would you mind trying to remove the `defined(__CUDACC__)` from this line: https://github.com/STEllAR-GROUP/hpx/blob/da74ce25e3e3bb59d00b7d877216958f799f888f/libs/full/include/include/hpx/include/compute.hpp#L10. I'll try to get the exercises actually fixed upstream for you soon as well.

**Comment by ghost** [comment]
Thank you for your reponse @msimberg. I tried your suggestion but HPX build fails due to that change. I've pasted a file containing the error. 
[a.txt](https://github.com/STEllAR-GROUP/tutorials/files/5592720/a.txt)

**Comment by msimberg** [comment]
@nithin-nod I've just pushed a lot of changes which update the exercises to work with latest master.

The CUDA example you tried to build should also build now. However, `hpx::reduce` does not work with the CUDA executor. The exercise has my name in it but I can't really explain what I was thinking when I wrote that... In general the CUDA executor in HPX only supports regular data parallel algorithms. I've updated the exercise to use `hpx::for_each`.

Support for algorithms with the current HPX CUDA executor is unlikely to get better. If you're interested specifically in `hpx::reduce` on CUDA GPUs there is support for that in the Kokkos interop repo: https://github.com/STEllAR-GROUP/hpx-kokkos. This is still early work, but if that's something you're interested in I'd be happy to help you get started there.

In general the best place to look for up-to-date examples is in the HPX repo itself since those are checked by CI. Some of the CUDA examples can be found there as well in a working form: https://github.com/STEllAR-GROUP/hpx/tree/master/libs/full/async_cuda/tests/unit. There are more here: https://github.com/STEllAR-GROUP/hpx/tree/master/libs/full/compute_cuda/tests/unit and here: https://github.com/STEllAR-GROUP/hpx/tree/master/libs/full/compute_cuda/examples. We'll have to do some cleanup in this repo, i.e. probably move the examples to the main HPX repo.

**Comment by ghost** [comment]
@msimberg Thank you for your inputs, I was able to get a cuda working example from this link (https://github.com/STEllAR-GROUP/hpx/tree/master/libs/full/compute_cuda/examples) that you suggested. Should a need for reduction on GPUs arise I'll definitely ask for help, thank you for your offer
.

**Comment by AmosLewis** [comment]
Is there any example that cuda+hpx runs on multiple nodes?

**Comment by AmosLewis** [comment]
> @nithin-nod I've just pushed a lot of changes which update the exercises to work with latest master.
> 
> The CUDA example you tried to build should also build now. However, `hpx::reduce` does not work with the CUDA executor. The exercise has my name in it but I can't really explain what I was thinking when I wrote that... In general the CUDA executor in HPX only supports regular data parallel algorithms. I've updated the exercise to use `hpx::for_each`.
> 
> Support for algorithms with the current HPX CUDA executor is unlikely to get better. If you're interested specifically in `hpx::reduce` on CUDA GPUs there is support for that in the Kokkos interop repo: https://github.com/STEllAR-GROUP/hpx-kokkos. This is still early work, but if that's something you're interested in I'd be happy to help you get started there.
> 
> In general the best place to look for up-to-date examples is in the HPX repo itself since those are checked by CI. Some of the CUDA examples can be found there as well in a working form: https://github.com/STEllAR-GROUP/hpx/tree/master/libs/full/async_cuda/tests/unit. There are more here: https://github.com/STEllAR-GROUP/hpx/tree/master/libs/full/compute_cuda/tests/unit and here: https://github.com/STEllAR-GROUP/hpx/tree/master/libs/full/compute_cuda/examples. We'll have to do some cleanup in this repo, i.e. probably move the examples to the main HPX repo.

Is there any example that cuda+hpx runs on multiple nodes?
